name = "LocalProjections"
uuid = "42571009-22de-48df-b2d5-611d176495e8"
version = "0.1.0"

[deps]
CovarianceMatrices = "60f91f6f-d783-54cb-84f9-544141854719"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
Missings = "e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ShiftedArrays = "1277b4bf-5013-50f5-be3d-901d8477a67a"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsModels = "3eaba693-59b7-5ba5-a881-562e759f1c8d"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"

[compat]
julia = "1.10"
CovarianceMatrices = "0.10, 0.30"
DataFrames = "1"
Distributions = "0.25"
GLM = "1"
Plots = "1"
ShiftedArrays = "2"
StatsBase = "0.34"
StatsModels = "0.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"

[targets]
test = ["Test", "TestItemRunner"]
