[deps]
CovarianceMatrices = "60f91f6f-d783-54cb-84f9-544141854719"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
LocalProjections = "42571009-22de-48df-b2d5-611d176495e8"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
StatsModels = "3eaba693-59b7-5ba5-a881-562e759f1c8d"

[sources]
LocalProjections = {path = ".."}
